general:
  EnableTextMail: true
  EnableItemMail: true
  EnableEnderchest: true
  EnableMailCosts: false
  EnablePerItemCosts: false
  EnableSendMoney: false
  CostToText: 0.0
  SendItemCost: 0.0
  MailWindowRows: 3
  DefaultBoxRows: 4
  EnderChestRequirementID: 368
  EnderChestRequirementDV: 0
  CurrencyItemID: 266
  MailItemID: 339
  MailItemDV: 1
  BankNoteID: 339
  MailItemName: Briefpapier
  NewMailGuiTitle: 'Neuen Brief verfassen:'
  InboxGuiTitle: 'Postfach:'
  CreateMailItemLore: 'Nimm dies zur Hand, um einen neuen Brief zu verfassen.'
  MailItemIngredients: 'PAPER,FEATHER,INK_SACK'
  SignText: Briefkasten
messages:
  inbox-full-send: Der Briefkasten von %recipient% ist voll, die Gegenstände wurden an dich zurückgeschickt.
  ingredient-missing: Du besitzt kein %item%, um einen neuen Brief zu erstellen.
inboxPlayers: []
