name: ArathosMail
version: 1.0.1.4
author: DrkMatr1984 | edited by fmaster
main: com.github.derwisch.paperMail.PaperMail
softdepend: [Vault]
      
commands:
   papermail:
      usage: /papermail <sendtext|createbox>
      aliases: [pm]
      
permissions:
    papermail.*:
        description: Zugriff auf alle Funktionen des Plugins
        children:
            papermail.send.text: true
            papermail.send.item.box: true
            papermail.createchest.self: true
            papermail.createchest.everyone: true
            papermail.costs.exempt: true
    papermail.send.text:
        description: Erlaubt Textnachrichten zu verschicken
        default: true
    papermail.send.item:
        description: Erlaubt Nachrichten ueber Briefkaesten zu senden
        default: true
    papermail.createchest.self:
        description: Erlaubt Briefkaesten fuer Spieler zu erstellen
        default: true
    papermail.createchest.everyone:
        description: Erlaubt oeffentliche Briefkaesten zu erstellen
        default: false
        children:
            papermail.createchest.self: true
    papermail.costs.exempt:
        description: Briefe immer kostenlos, auch wenn Kosten eingestellt sind
        default: false
        
